apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe -f docker-compose.yml -f docker-compose.override.yml -o ../k8s --volumes hostPath convert
    kompose.service.type: loadbalancer
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: db-tcp
  name: db-tcp
  namespace: default
spec:
  ports:
    - name: "6000"
      port: 6000
      targetPort: 5432
  selector:
    io.kompose.service: db
  type: LoadBalancer
status:
  loadBalancer: {}
