apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe -f docker-compose.yml -f docker-compose.override.yml -o ../k8s --volumes hostPath convert
    kompose.service.type: loadbalancer
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.service: graylog-tcp
  name: graylog-tcp
  namespace: default
spec:
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
    - name: "1514"
      port: 1514
      targetPort: 1514
    - name: "12201"
      port: 12201
      targetPort: 12201
  selector:
    io.kompose.service: graylog
  type: LoadBalancer
status:
  loadBalancer: {}
