apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe -f docker-compose.yml -f docker-compose.override.yml -o ../k8s --volumes hostPath convert
    kompose.image-pull-policy: IfNotPresent
    kompose.service.type: loadbalancer
    kompose.version: 1.30.0 (9d8dcb518)
  creationTimestamp: null
  labels:
    io.kompose.network/docker-default: "true"
    io.kompose.service: web
  name: web
  namespace: default
spec:
  containers:
    - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Docker
        - name: ASPNETCORE_URLS
          value: http://+:8082
      image: force-web
      imagePullPolicy: IfNotPresent
      name: web
      ports:
        - containerPort: 8082
          hostPort: 6001
          protocol: TCP
      resources: {}
  restartPolicy: OnFailure
status: {}
