version: '1.0'

services:
  
  web:
    image: force-web
    build:
      context: ../
      dockerfile: ./src/WebApp.Web/Dockerfile
    restart: always
    environment:
      - ASPNETCORE_URLS=http://+:8082
      - "ASPNETCORE_ENVIRONMENT=Docker"
    ports:
      - target: 8082
        published: 6001
        protocol: tcp
        mode: host
    depends_on:
      - db

  db:
    image: "postgres:15"
    restart: on-failure
    environment:
      - POSTGRES_DB=force_db
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - web-app-db:/var/lib/postgresql/data:rw
    ports:
      - target: 5432
        published: 6000
        protocol: tcp
        mode: host
  gray-log:
    image: "graylog/graylog:5.1"
    environment:
    - GRAYLOG_PASSWORD_SECRET=979b216733674aadb0fee5e410c2c57d
    - GRAYLOG_ROOT_PASSWORD_SHA2=d9c8198bd0562d11363661d8a2c3d297a0a3bab88291c10ae2c26689209efba5
    restart: on-failure
    depends_on:
    - mongo
    - elasticsearch
    ports:
    - 9000:9000
    - 1514:1514
    - 1514:1514/udp
    - 12201:12201
    - 12201:12201/udp
  mongo:
    image: mongo:5.0.13
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Dlog4j2.formatMsgNoLookups=true -Xms512m -Xmx512m"


volumes:
  web-app-db: 
